In [1]:
import torch
import numpy as np

In [2]:
x = torch.Tensor(4,2)
print(x.shape)
print(x.type())
print(x)

torch.Size([4, 2])
torch.FloatTensor
tensor([[3.4065e-05, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [2.8175e+20, 1.7566e+25],
        [1.7748e+28, 0.0000e+00]])


In [3]:
x = torch.randn(4,2)
print(x)

tensor([[-0.2747, -1.6726],
        [ 1.0553,  0.1154],
        [-1.8894, -0.4363],
        [ 0.8617,  0.6822]])


In [4]:
x = torch.rand(4,2)
print(x)

tensor([[0.7355, 0.8325],
        [0.3556, 0.5837],
        [0.7332, 0.1187],
        [0.6938, 0.8732]])


In [5]:
x = torch.ones(4,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [6]:
x = torch.zeros(4,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
l1 = []
l2 = []
for i in range(1,9):
    if i%2 ==0 :
        l1.append(i)
    else:
        l2.append(i)
print(l1)
print(l2)

[2, 4, 6, 8]
[1, 3, 5, 7]


In [8]:
x = torch.Tensor([l1,l2])
print(x.shape)
print(x.type())
print(x)

torch.Size([2, 4])
torch.FloatTensor
tensor([[2., 4., 6., 8.],
        [1., 3., 5., 7.]])


In [9]:
x = np.random.rand(4,2)
print(x)
x1 = torch.from_numpy(x)
print(x1.shape)
print(x1.type())
print(x1)
x1.long()
print(x1.type())

[[0.01990771 0.75868795]
 [0.19489275 0.51518399]
 [0.60818342 0.07595875]
 [0.80795935 0.06200587]]
torch.Size([4, 2])
torch.DoubleTensor
tensor([[0.0199, 0.7587],
        [0.1949, 0.5152],
        [0.6082, 0.0760],
        [0.8080, 0.0620]], dtype=torch.float64)
torch.DoubleTensor


In [10]:
x = torch.ones(4,2)
y = torch.randn(4,2)
print(y)
print(x+y)

tensor([[-0.9444,  0.6451],
        [ 0.1270, -0.1355],
        [-2.5650,  0.1729],
        [-0.2216, -0.9316]])
tensor([[ 0.0556,  1.6451],
        [ 1.1270,  0.8645],
        [-1.5650,  1.1729],
        [ 0.7784,  0.0684]])


In [11]:
x = torch.randn(4,2)
y = torch.randn(2,4)
z = torch.mm(x,y)
print(z.shape)
k = torch.mm(y,x)
print(k.shape)

torch.Size([4, 4])
torch.Size([2, 2])


In [12]:
x = torch.randn(4,2)
y = torch.t(x)
z = torch.mm(x,y)
print(z)

tensor([[0.0022, 0.0107, 0.0308, 0.0242],
        [0.0107, 0.8869, 1.1180, 0.2661],
        [0.0308, 1.1180, 1.5575, 0.5147],
        [0.0242, 0.2661, 0.5147, 0.2966]])


In [13]:
x = torch.randn(4,1)
print(x)
print(x.view(2,2))
print(x.view(1,4))

tensor([[ 1.0378],
        [ 0.6430],
        [-0.8269],
        [-0.1953]])
tensor([[ 1.0378,  0.6430],
        [-0.8269, -0.1953]])
tensor([[ 1.0378,  0.6430, -0.8269, -0.1953]])


In [14]:
x = torch.ones(4,2)
print(x)
z = torch.sum(x,dim = 0)
print(z)
z = torch.sum(x,dim = 1)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([4., 4.])
tensor([2., 2., 2., 2.])


In [15]:
x = torch.randn(4,2)
print(x)
print(x[:1])
print(x[:2])
print(x[:3])
print(x[:,0])
print(x[:,1])
print(x[1:3,1])

tensor([[-0.2633,  0.8818],
        [ 2.0058, -0.8544],
        [ 0.1556, -0.3123],
        [-0.6143, -0.5345]])
tensor([[-0.2633,  0.8818]])
tensor([[-0.2633,  0.8818],
        [ 2.0058, -0.8544]])
tensor([[-0.2633,  0.8818],
        [ 2.0058, -0.8544],
        [ 0.1556, -0.3123]])
tensor([-0.2633,  2.0058,  0.1556, -0.6143])
tensor([ 0.8818, -0.8544, -0.3123, -0.5345])
tensor([-0.8544, -0.3123])


In [16]:
x = torch.randn(3,3)
print(x)
print("--- --- --- ---")
col_index = torch.LongTensor([0,2])
y = torch.index_select(x,dim = 1, index = col_index)
print(y)
print("--- --- --- ---")
z = torch.index_select(x,dim=0,index = col_index)
print(z)

tensor([[ 0.2367,  0.1566, -1.3267],
        [-1.2587, -1.0848, -1.2562],
        [-1.6150, -0.6484, -0.5649]])
--- --- --- ---
tensor([[ 0.2367, -1.3267],
        [-1.2587, -1.2562],
        [-1.6150, -0.5649]])
--- --- --- ---
tensor([[ 0.2367,  0.1566, -1.3267],
        [-1.6150, -0.6484, -0.5649]])


In [17]:
x = torch.randn(4,1)
print(x)
print("----- ----- ----- -----")
y = torch.cat([x,x],dim=0)
print(y)
print("----- ----- ----- -----")
z = torch.cat([x,x],dim=1)
print(z)

tensor([[ 1.5584],
        [ 0.5313],
        [-0.9380],
        [ 0.2667]])
----- ----- ----- -----
tensor([[ 1.5584],
        [ 0.5313],
        [-0.9380],
        [ 0.2667],
        [ 1.5584],
        [ 0.5313],
        [-0.9380],
        [ 0.2667]])
----- ----- ----- -----
tensor([[ 1.5584,  1.5584],
        [ 0.5313,  0.5313],
        [-0.9380, -0.9380],
        [ 0.2667,  0.2667]])


In [18]:
# for gradient!!
x = torch.randn(3,4,requires_grad = True)
print(x)

tensor([[ 0.9503,  0.4713,  0.3010,  0.7411],
        [ 0.1790, -1.5959, -0.1162,  1.0975],
        [-0.4154,  0.4071, -0.5964,  1.2852]], requires_grad=True)


In [19]:
y = 3*x + 2
print(y)

tensor([[ 4.8508,  3.4138,  2.9031,  4.2232],
        [ 2.5371, -2.7878,  1.6514,  5.2924],
        [ 0.7539,  3.2213,  0.2107,  5.8556]], grad_fn=<AddBackward0>)


In [20]:
z = y.mean()
print(z)

tensor(2.6771, grad_fn=<MeanBackward0>)


In [21]:
#z.backward(retain_graph = True)
z.backward()

In [22]:
print(z)

tensor(2.6771, grad_fn=<MeanBackward0>)


In [23]:
print(x)

tensor([[ 0.9503,  0.4713,  0.3010,  0.7411],
        [ 0.1790, -1.5959, -0.1162,  1.0975],
        [-0.4154,  0.4071, -0.5964,  1.2852]], requires_grad=True)


In [24]:
zx = x.grad
print(zx)

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


In [ ]:
# for CUDA

In [26]:
print(torch.cuda.is_available())

True


In [28]:
x = torch.Tensor(3,4).to("cpu")
print(x.type())

torch.FloatTensor


In [29]:
x = torch.Tensor(3,4)
print(x.type())

torch.FloatTensor


In [30]:
x = torch.Tensor(3,4).to("cuda")
print(x.type())

torch.cuda.FloatTensor
